import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const crateDir = path.join(rootDir, "crates", "charts-density-wasm");
const sourcePaths = [
  "crates/charts-density-wasm/.cargo/config.toml",
  "crates/charts-density-wasm/Cargo.lock",
  "crates/charts-density-wasm/Cargo.toml",
  "crates/charts-density-wasm/src/lib.rs",
];

execFileSync("rustup", ["target", "add", "wasm32-unknown-unknown"], {
  cwd: crateDir,
  stdio: "inherit",
});
execFileSync("cargo", ["build", "--target", "wasm32-unknown-unknown", "--release", "--locked"], {
  cwd: crateDir,
  stdio: "inherit",
});

const wasmPath = path.join(
  crateDir,
  "target",
  "wasm32-unknown-unknown",
  "release",
  "charts_density_wasm.wasm",
);
const outputPath = path.join(rootDir, "src", "wasm", "generated.ts");
const wasm = readFileSync(wasmPath);
const sourceHash = hashSources();

mkdirSync(path.dirname(outputPath), { recursive: true });
writeFileSync(
  outputPath,
  [
    "// Generated by scripts/build-wasm.mjs. Do not edit by hand.",
    `// source-sha256:${sourceHash}`,
    "/* prettier-ignore */",
    `export const CHART_WASM_BASE64: string | null = ${JSON.stringify(wasm.toString("base64"))};`,
    "",
  ].join("\n"),
);

console.log(`Built charts-density-wasm (${wasm.length} bytes, source ${sourceHash.slice(0, 12)}).`);

function hashSources() {
  const hash = createHash("sha256");

  for (const relativePath of sourcePaths) {
    hash.update(relativePath);
    hash.update("\0");
    hash.update(readFileSync(path.join(rootDir, relativePath)));
    hash.update("\0");
  }

  return hash.digest("hex");
}
