type GeneratedChartsWasmModule = {
  default?: (input?: unknown) => Promise<unknown> | unknown;
  aggregate_density_bins: (
    x: Float64Array,
    y: Float64Array,
    domainMin: number,
    domainMax: number,
    binCount: number,
  ) => unknown;
  aggregate_histogram: (
    values: Float64Array,
    domainMin: number,
    domainMax: number,
    bucketCount: number,
  ) => unknown;
  percentile: (values: Float64Array, quantile: number) => number;
};

type NodeFileReader = {
  readFile(path: URL | string): Promise<Uint8Array>;
};

type NodeRuntimeProcess = {
  cwd(): string;
  versions?: {
    node?: string;
  };
};

export type ChartWasmDensityBin = {
  averageY: number | null;
  index: number;
  maxY: number | null;
  minY: number | null;
  pointCount: number;
  sumY: number;
  x0: number;
  x1: number;
};

export type ChartWasmHistogramBucket = {
  averageValue: number | null;
  index: number;
  maxValue: number | null;
  minValue: number | null;
  pointCount: number;
  sumValue: number;
  value0: number;
  value1: number;
};

export type ChartWasmKernel = {
  aggregateDensityBins(
    x: Float64Array,
    y: Float64Array,
    domain: [number, number],
    binCount: number,
  ): ChartWasmDensityBin[];
  aggregateHistogram(
    values: Float64Array,
    domain: [number, number],
    bucketCount: number,
  ): ChartWasmHistogramBucket[];
  percentile(values: Float64Array, quantile: number): number;
};

let loadedKernel: ChartWasmKernel | null = null;
let loadingKernel: Promise<ChartWasmKernel> | null = null;

export function getLoadedChartWasmKernel() {
  return loadedKernel;
}

export async function loadChartWasmKernel(): Promise<ChartWasmKernel> {
  if (loadedKernel) {
    return loadedKernel;
  }
  if (loadingKernel) {
    return loadingKernel;
  }

  loadingKernel = loadGeneratedModule().then((module) => {
    const kernel: ChartWasmKernel = {
      aggregateDensityBins(x, y, domain, binCount) {
        const bins = module.aggregate_density_bins(x, y, domain[0], domain[1], binCount);
        return normalizeBins(bins);
      },
      aggregateHistogram(values, domain, bucketCount) {
        const buckets = module.aggregate_histogram(
          values,
          domain[0],
          domain[1],
          bucketCount,
        );
        return normalizeHistogramBuckets(buckets);
      },
      percentile(values, quantile) {
        return module.percentile(values, quantile);
      },
    };
    loadedKernel = kernel;
    return kernel;
  });

  try {
    return await loadingKernel;
  } finally {
    loadingKernel = null;
  }
}

async function loadGeneratedModule(): Promise<GeneratedChartsWasmModule> {
  // Vite executes this source module directly after build:wasm, while published bundles copy the
  // same wasm-pack output next to dist/*.js. Keep both layouts explicit so source execution does
  // not probe a known-missing production path and emit a browser 404 before falling back to JS.
  const currentModuleUrl = new URL(import.meta.url);
  const usesSourceLayout = currentModuleUrl.pathname.endsWith(".ts");
  const generatedModulePath = usesSourceLayout
    ? "./wasm/generated/charts_density_wasm.js"
    : "./wasm/charts_density_wasm.js";
  const generatedWasmPath = usesSourceLayout
    ? "./wasm/generated/charts_density_wasm_bg.wasm"
    : "./wasm/charts_density_wasm_bg.wasm";
  const moduleUrl = new URL(generatedModulePath, currentModuleUrl).href;
  const module = (await import(/* @vite-ignore */ moduleUrl)) as GeneratedChartsWasmModule;
  const nodeProcess = readNodeProcess();

  if (nodeProcess?.versions?.node) {
    // wasm-pack's web target defaults to fetching its sibling .wasm URL. Under Vitest/Vite that
    // URL can be represented as localhost even though no test server is serving it. Feed the exact
    // generated bytes instead. Packaged Node consumers resolve relative to their installed module;
    // the cwd fallback is only for Vite's virtualized source-module URL during tests.
    const nodeFsSpecifier = "node:fs/promises";
    const nodeFs = (await import(/* @vite-ignore */ nodeFsSpecifier)) as NodeFileReader;
    const wasmUrl = new URL(generatedWasmPath, currentModuleUrl);
    const wasmBytes =
      wasmUrl.protocol === "file:"
        ? await nodeFs.readFile(wasmUrl)
        : await nodeFs.readFile(
            `${nodeProcess.cwd()}/${usesSourceLayout ? "src/wasm/generated" : "dist/wasm"}/charts_density_wasm_bg.wasm`,
          );

    await module.default?.(wasmBytes);
  } else {
    await module.default?.();
  }

  return module;
}

function readNodeProcess(): NodeRuntimeProcess | null {
  const runtimeGlobal = globalThis as typeof globalThis & {
    process?: NodeRuntimeProcess;
  };

  return runtimeGlobal.process ?? null;
}

function normalizeBins(value: unknown): ChartWasmDensityBin[] {
  if (!Array.isArray(value)) {
    throw new TypeError("charts WASM aggregate_density_bins returned a non-array result");
  }

  return value.map((entry, index) => {
    if (!entry || typeof entry !== "object") {
      throw new TypeError(`charts WASM bin ${index} is not an object`);
    }
    const bin = entry as Record<string, unknown>;
    return {
      averageY: readNullableNumber(bin.averageY),
      index: readNumber(bin.index, "index"),
      maxY: readNullableNumber(bin.maxY),
      minY: readNullableNumber(bin.minY),
      pointCount: readNumber(bin.pointCount, "pointCount"),
      sumY: readNumber(bin.sumY, "sumY"),
      x0: readNumber(bin.x0, "x0"),
      x1: readNumber(bin.x1, "x1"),
    };
  });
}

function normalizeHistogramBuckets(value: unknown): ChartWasmHistogramBucket[] {
  if (!Array.isArray(value)) {
    throw new TypeError("charts WASM aggregate_histogram returned a non-array result");
  }

  return value.map((entry, index) => {
    if (!entry || typeof entry !== "object") {
      throw new TypeError(`charts WASM histogram bucket ${index} is not an object`);
    }
    const bucket = entry as Record<string, unknown>;
    return {
      averageValue: readNullableNumber(bucket.averageValue),
      index: readNumber(bucket.index, "index"),
      maxValue: readNullableNumber(bucket.maxValue),
      minValue: readNullableNumber(bucket.minValue),
      pointCount: readNumber(bucket.pointCount, "pointCount"),
      sumValue: readNumber(bucket.sumValue, "sumValue"),
      value0: readNumber(bucket.value0, "value0"),
      value1: readNumber(bucket.value1, "value1"),
    };
  });
}

function readNumber(value: unknown, key: string) {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    throw new TypeError(`charts WASM bin field ${key} must be a finite number`);
  }
  return value;
}

function readNullableNumber(value: unknown) {
  return value == null ? null : readNumber(value, "numeric aggregate");
}
